# Kronos Intelligence
## Student Performance Classification

# Notebook 06: Model Evaluation & Business Recommendations

---

## Project Overview

In the previous notebook, multiple machine learning algorithms were developed and evaluated to predict student academic success.

This notebook focuses on interpreting those results, comparing model performance from both technical and business perspectives, and developing actionable recommendations for educational institutions.

The objective is to identify the model that provides the best balance of predictive performance, interpretability, and practical implementation while supporting the ethical and responsible use of predictive analytics in education.

---

**Prepared by:** Tessa Gonzalez

**Organization:** Kronos Intelligence

**Project:** Student Performance Classification

**Notebook:** 06 of 07

# Objectives

By the end of this notebook, we will:

- Review the performance of all machine learning models developed during the project.
- Compare models using multiple evaluation metrics.
- Evaluate the strengths and limitations of each algorithm.
- Recommend the most appropriate model for deployment.
- Discuss ethical, governance, and implementation considerations.
- Develop actionable recommendations for educational institutions.
- Summarize project findings and identify future opportunities for improvement.

In [1]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import os
import joblib

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from google.colab import drive

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

In [2]:
# ==========================================================
# Project Environment
# ==========================================================

drive.mount('/content/drive')

PROJECT_ROOT = "/content/drive/MyDrive/Kronos Intelligence/Student Performance Classification"

MODEL_DATA = os.path.join(PROJECT_ROOT, "data", "model")

MODELS = os.path.join(PROJECT_ROOT, "models")

print("✅ Project Ready")

Mounted at /content/drive
✅ Project Ready

# Load Trained Models

The machine learning models developed in Notebook 05 are loaded for evaluation and comparison.

Loading previously trained models improves reproducibility and reflects a common production workflow in which models are trained once and reused for evaluation, deployment, and monitoring.

In [3]:
# ==========================================================
# Load Trained Models
# ==========================================================

log_model = joblib.load(
    os.path.join(MODELS, "logistic_regression.pkl")
)

tree_model = joblib.load(
    os.path.join(MODELS, "decision_tree.pkl")
)

rf_model = joblib.load(
    os.path.join(MODELS, "random_forest.pkl")
)

gb_model = joblib.load(
    os.path.join(MODELS, "gradient_boosting.pkl")
)

print("✅ All trained models loaded successfully.")

✅ All trained models loaded successfully.

# Load Evaluation Dataset

The testing dataset created during feature engineering is loaded to evaluate model performance.

Using the same unseen testing data for each model ensures that comparisons remain fair, consistent, and reproducible.

In [4]:
# ==========================================================
# Load Test Dataset
# ==========================================================

X_test = pd.read_csv(
    os.path.join(MODEL_DATA, "X_test.csv")
)

y_test = pd.read_csv(
    os.path.join(MODEL_DATA, "y_test.csv")
).squeeze()

print("Testing Features:", X_test.shape)
print("Testing Labels:", y_test.shape)

Testing Features: (2000, 10029)
Testing Labels: (2000,)

# Review of Notebook 05

Notebook 05 focused on developing and comparing multiple supervised machine learning models for predicting student academic success.

The following algorithms were trained and evaluated:

- Logistic Regression
- Decision Tree
- Random Forest
- Gradient Boosting

Model performance was assessed using Accuracy, Precision, Recall, F1 Score, ROC-AUC, classification reports, confusion matrices, and feature importance analysis.

Gradient Boosting achieved the highest overall ROC-AUC score and emerged as the strongest-performing model, while Random Forest provided valuable insights into the relative importance of the predictor variables.

# Model Decision Matrix

## Business Question

**Which machine learning model provides the best balance of predictive performance, interpretability, operational efficiency, and business value?**

Selecting a machine learning model involves more than identifying the algorithm with the highest accuracy or ROC-AUC score. Organizations must also consider how easily a model can be interpreted, deployed, maintained, and trusted by stakeholders.

This decision matrix evaluates each model using technical performance metrics alongside practical business considerations to identify the most appropriate solution for an educational early warning system.

In [5]:
# ==========================================================
# Model Decision Matrix
# ==========================================================

decision_matrix = pd.DataFrame({

    "Evaluation Criterion": [

        "Predictive Performance",
        "Interpretability",
        "Computational Efficiency",
        "Ease of Deployment",
        "Business Suitability"

    ],

    "Logistic Regression": [

        "★★★★☆",
        "★★★★★",
        "★★★★★",
        "★★★★★",
        "★★★★☆"

    ],

    "Decision Tree": [

        "★★★☆☆",
        "★★★★★",
        "★★★★☆",
        "★★★★☆",
        "★★★★☆"

    ],

    "Random Forest": [

        "★★★★☆",
        "★★★☆☆",
        "★★★☆☆",
        "★★★☆☆",
        "★★★★★"

    ],

    "Gradient Boosting": [

        "★★★★★",
        "★★☆☆☆",
        "★★☆☆☆",
        "★★★☆☆",
        "★★★★★"

    ]

})

decision_matrix

,Evaluation Criterion,Logistic Regression,Decision Tree,Random Forest,Gradient Boosting
0,Predictive Performance,★★★★☆,★★★☆☆,★★★★☆,★★★★★
1,Interpretability,★★★★★,★★★★★,★★★☆☆,★★☆☆☆
2,Computational Efficiency,★★★★★,★★★★☆,★★★☆☆,★★☆☆☆
3,Ease of Deployment,★★★★★,★★★★☆,★★★☆☆,★★★☆☆
4,Business Suitability,★★★★☆,★★★★☆,★★★★★,★★★★★

# Save Final Model Ranking

The final model comparison table is saved for use in the executive report.

Saving evaluation results ensures consistency across project deliverables and supports reproducible reporting.

In [8]:
# ==========================================================
# Recreate Model Results Table
# ==========================================================

model_results = pd.DataFrame({

    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],

    "Accuracy": [
        0.9610,
        0.8765,
        0.9610,
        0.9650
    ],

    "Precision": [
        0.9610,
        0.9878,
        0.9610,
        0.9667
    ],

    "Recall": [
        1.0000,
        0.8824,
        1.0000,
        0.9979
    ],

    "F1 Score": [
        0.9801,
        0.9321,
        0.9801,
        0.9821
    ],

    "ROC AUC": [
        0.9127,
        0.8750,
        0.9296,
        0.9373
    ]

})

model_results

                 Model  Accuracy  Precision  Recall  F1 Score  ROC AUC
0  Logistic Regression    0.9610     0.9610  1.0000    0.9801   0.9127
1        Decision Tree    0.8765     0.9878  0.8824    0.9321   0.8750
2        Random Forest    0.9610     0.9610  1.0000    0.9801   0.9296
3    Gradient Boosting    0.9650     0.9667  0.9979    0.9821   0.9373

In [9]:
# ==========================================================
# Create Final Model Ranking
# ==========================================================

final_ranking = (
    model_results
    .sort_values(by="ROC AUC", ascending=False)
    .reset_index(drop=True)
)

final_ranking

                 Model  Accuracy  Precision  Recall  F1 Score  ROC AUC
0    Gradient Boosting    0.9650     0.9667  0.9979    0.9821   0.9373
1        Random Forest    0.9610     0.9610  1.0000    0.9801   0.9296
2  Logistic Regression    0.9610     0.9610  1.0000    0.9801   0.9127
3        Decision Tree    0.8765     0.9878  0.8824    0.9321   0.8750

In [10]:
# ==========================================================
# Save Final Model Ranking
# ==========================================================

REPORTS = os.path.join(PROJECT_ROOT, "reports")
os.makedirs(REPORTS, exist_ok=True)

final_ranking.to_csv(
    os.path.join(REPORTS, "model_ranking.csv"),
    index=False
)

print("✅ Final model ranking saved.")

✅ Final model ranking saved.

In [11]:
# ==========================================================
# Save Decision Matrix
# ==========================================================

decision_matrix.to_csv(
    os.path.join(REPORTS, "decision_matrix.csv"),
    index=False
)

print("✅ Decision matrix saved.")

✅ Decision matrix saved.

## Decision Matrix Interpretation

The decision matrix highlights that selecting a machine learning model requires balancing predictive performance with operational considerations.

Gradient Boosting achieved the highest predictive performance and business suitability, making it the strongest candidate for deployment within an educational early warning system. Although it is less interpretable than simpler algorithms, its superior ability to distinguish between students who are likely to pass and those who may require intervention makes it well suited for predictive analytics.

Random Forest also demonstrated strong predictive performance while providing feature importance estimates that improve model transparency. This makes it an attractive alternative when interpretability is an important organizational requirement.

Logistic Regression offered the greatest interpretability and computational efficiency, making it an excellent baseline model. However, its limited ability to identify students in the minority class reduced its practical usefulness for this application.

Decision Trees were highly interpretable but produced lower predictive performance than the ensemble learning methods.

Overall, Gradient Boosting is recommended as the preferred production model, while Random Forest provides valuable explanatory insights that can support stakeholder understanding and model validation.

# Executive Recommendation

Based on the evaluation conducted throughout this project, **Gradient Boosting** is recommended as the primary predictive model for identifying students who may be at academic risk.

This recommendation is based on several factors:

- Highest overall ROC-AUC score among the evaluated models.
- Strong predictive performance on unseen data.
- Ability to capture complex nonlinear relationships between behavioral and demographic variables.
- Robust performance despite class imbalance.

Although Gradient Boosting is less interpretable than Logistic Regression or a single Decision Tree, its predictive advantages outweigh this limitation for an early warning system whose primary objective is accurate identification of students requiring intervention.

To improve transparency, the organization should continue using Random Forest feature importance analyses to explain which variables most strongly influence predictions while deploying Gradient Boosting as the primary predictive engine.

This hybrid approach balances predictive accuracy with organizational trust and interpretability.

# Deployment Strategy

## Business Objective

The recommended Gradient Boosting model should be deployed as part of an educational early warning system designed to identify students who may be at academic risk early in the academic term.

Rather than replacing academic advisors or instructors, the model should function as a decision-support tool that helps prioritize proactive student interventions.

### Proposed Workflow

1. Collect updated student behavioral and academic engagement data.
2. Apply the same preprocessing pipeline developed during this project.
3. Generate risk predictions using the trained Gradient Boosting model.
4. Flag students with elevated risk scores.
5. Notify academic advisors for review.
6. Provide targeted support services based on individual student needs.
7. Monitor intervention outcomes and continuously evaluate model performance.

This workflow supports timely, data-driven decision making while maintaining human oversight throughout the intervention process.

# Implementation Roadmap

A phased implementation approach is recommended to reduce deployment risk and encourage stakeholder adoption.

| Phase | Objective |
|--------|-----------|
| Phase 1 | Validate the model using historical institutional data. |
| Phase 2 | Pilot the model with a limited group of academic advisors. |
| Phase 3 | Evaluate prediction accuracy and intervention outcomes. |
| Phase 4 | Deploy the model across the institution. |
| Phase 5 | Monitor model performance and retrain periodically using new student data. |

A phased deployment strategy allows institutions to refine predictive performance while minimizing operational disruption.

# Ethical and Governance Considerations

Predictive analytics should be implemented responsibly and transparently.

Key governance recommendations include:

- Protect student privacy through strong data governance practices.
- Limit access to sensitive educational information using role-based security.
- Regularly evaluate models for demographic bias and fairness.
- Retrain models periodically as student populations and behaviors evolve.
- Document preprocessing steps, model assumptions, and evaluation metrics to ensure reproducibility.
- Use predictions to support student success initiatives rather than punitive decision making.

Responsible governance improves stakeholder trust while promoting ethical use of predictive analytics.

# Business Recommendations

Based on the analysis conducted throughout this project, the following recommendations are proposed:

1. Deploy the Gradient Boosting model as the primary prediction engine for identifying students who may require academic intervention.
2. Continue using Random Forest feature importance to improve model transparency and explainability.
3. Prioritize behavioral variables such as study hours, attendance, motivation, stress level, and sleep when designing intervention programs.
4. Monitor model performance regularly and retrain the model using updated institutional data.
5. Integrate predictive analytics with existing student support services to enable proactive outreach.

These recommendations support evidence-based decision making while promoting improved student retention and academic success.

# Project Limitations

Several limitations should be considered when interpreting the results of this project:

- The dataset is synthetic and may not fully represent real-world student populations.
- The target variable is highly imbalanced, with substantially more students passing than failing.
- Model performance may vary when applied to different institutions or student populations.
- Additional feature engineering and hyperparameter tuning may further improve predictive performance.
- Future work should include external validation using institutional datasets before production deployment.

Despite these limitations, the project demonstrates a complete predictive analytics workflow suitable for adaptation to real educational environments.

# Final Project Conclusions

This project successfully developed an end-to-end predictive analytics solution for identifying students who may be at academic risk.

The project included:

- Data understanding
- Data cleaning
- Exploratory data analysis
- Feature engineering
- Machine learning model development
- Model evaluation
- Business recommendations

Among the evaluated algorithms, Gradient Boosting demonstrated the strongest overall predictive performance, while Random Forest provided valuable feature importance insights that improved model interpretability.

The analysis showed that behavioral variables—including study hours, attendance, motivation, stress level, and sleep—were stronger predictors of academic success than demographic characteristics.

Overall, this project demonstrates how predictive analytics can support educational institutions by enabling earlier interventions, improving student success, and supporting data-driven decision making.

---

# Kronos Intelligence Portfolio Progress

| Notebook | Status |
|----------|--------|
| 01 — Data Understanding | ✅ Complete |
| 02 — Data Cleaning | ✅ Complete |
| 03 — Exploratory Data Analysis | ✅ Complete |
| 04 — Feature Engineering & Data Preparation | ✅ Complete |
| 05 — Machine Learning Model Development | ✅ Complete |
| 06 — Model Evaluation & Business Recommendations | ✅ Complete |
| 07 — Executive Report & Portfolio Presentation | ⏳ Next |

---

**Prepared by**

**Tessa Gonzalez**  
Founder & Data Analyst  
**Kronos Intelligence**

*Data Analytics • Predictive Analytics • Data Governance*